services:
  frontend:
    container_name: lvm-frontend-app
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ../app/frontend/:/app
      - /app/node_modules
    ports:
      - "${PORT:-3000}:8000"
    stdin_open: true
    tty: true
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - lvm_internal

networks:
  lvm_internal:
    driver: bridge
    name: lvm_internal